cabal-version:   3.0
name:            burogu
version:         0.1.0.0
license:         AGPL-3.0-or-later
license-file:    LICENSE
maintainer:      creeperblin@outlook.com
author:          moe li
homepage:        lizi.moe
category:        Web
build-type:      Simple

executable burogu
    main-is:          Main.hs
    other-modules:    Build
                    , Cli
                    , Config
                    , Css
                    , Deploy
                    , Env
                    , Feed
                    , Html
                    , Init
                    , NewPost
                    , Paths_burogu
                    , Post
                    , Sitemap
                    , Site
                    , Sync
                    , Watch
    hs-source-dirs:   app
    default-language: GHC2021
    default-extensions: OverloadedStrings
    ghc-options:      -Wall
    build-depends:    base ^>=4.18.3.0
                    , aeson
                    , containers
                    , clay
                    , directory
                    , filepath
                    , bytestring
                    , lucid
                    , network
                    , optparse-applicative
                    , pandoc
                    , pandoc-types
                    , process
                    , text
                    , time
                    , yaml

test-suite burogu-test
    type:             exitcode-stdio-1.0
    main-is:          PostSpec.hs
    other-modules:    Build
                    , Cli
                    , Config
                    , Css
                    , Deploy
                    , Env
                    , Feed
                    , Html
                    , Init
                    , NewPost
                    , Paths_burogu
                    , Post
                    , Sitemap
                    , Site
                    , Sync
                    , Watch
    hs-source-dirs:   test
                    , app
    default-language: GHC2021
    default-extensions: OverloadedStrings
    ghc-options:      -Wall
    build-depends:    base ^>=4.18.3.0
                    , aeson
                    , containers
                    , clay
                    , directory
                    , filepath
                    , bytestring
                    , lucid
                    , network
                    , optparse-applicative
                    , pandoc
                    , pandoc-types
                    , process
                    , tasty
                    , tasty-hunit
                    , text
                    , time
                    , yaml
