module Registry (SitePages (..), classifyPages, defaultArchiveTitle, defaultSearchTitle, defaultTagsLabel, navItems, specialPages, specialURLList) where

import Data.List (find, sortOn)
import Data.Maybe (fromMaybe)
import Data.Text (Text)
import Data.Text qualified as T
import Page (CustomPage (..))

{- | The classified pages: special pages (declared via redirectAs) are
pulled out of the normal page list. Special pages keep their file slug.
-}
data SitePages = SitePages
    { sp404 :: Maybe (Text, CustomPage)
    , spTags :: Maybe (Text, CustomPage)
    , spArchive :: Maybe (Text, CustomPage)
    , spSearch :: Maybe (Text, CustomPage)
    , spNormal :: [(Text, CustomPage)]
    }

{- | Registered special-page URLs. A page whose frontmatter declares one
of these via `redirectAs` becomes the corresponding special page; its
content is generated by burogu at that URL instead of the markdown body.
-}
specialURLs :: [(Text, Text)]
specialURLs = [("/404.html", "404"), ("/tags/", "tags"), ("/archive/", "archive"), ("/search/", "search")]

specialURLList :: Text
specialURLList = T.intercalate ", " (map fst specialURLs)

defaultTagsLabel :: Text
defaultTagsLabel = "Tags"

defaultArchiveTitle :: Text
defaultArchiveTitle = "Archive"

defaultSearchTitle :: Text
defaultSearchTitle = "Search"

{- | Classify loaded pages: validate the redirectAs declarations (known
URLs, no duplicates, no slug collisions) and split special pages out.
-}
classifyPages :: [(Text, CustomPage)] -> Either [Text] SitePages
classifyPages pages
    | null errs = Right sitePages
    | otherwise = Left errs
  where
    specials = [(slug, page) | (slug, page) <- pages, cpRedirectAs page /= Nothing]
    normals = [(slug, page) | (slug, page) <- pages, cpRedirectAs page == Nothing]
    sitePages =
        SitePages
            { sp404 = findByURL "/404.html" specials
            , spTags = findByURL "/tags/" specials
            , spArchive = findByURL "/archive/" specials
            , spSearch = findByURL "/search/" specials
            , spNormal = normals
            }
    errs = unknownURLErrs <> duplicateErrs <> collisionErrs
    unknownURLErrs =
        [ "unknown redirectAs '" <> url <> "' in _pages/" <> slug <> ".md (redirectAs is only for special pages: " <> specialURLList <> "; remove it to make a normal page at " <> "/" <> slug <> "/)"
        | (slug, page) <- specials
        , let url = canonical page
        , url `notElem` map fst specialURLs
        ]
    duplicateErrs =
        [ "duplicate declaration of '" <> url <> "': used by " <> T.intercalate ", " ["_pages/" <> slug <> ".md" | slug <- users]
        | url <- map fst specialURLs
        , let users = [slug | (slug, page) <- specials, canonical page == url]
        , length users > 1
        ]
    collisionErrs =
        [ "normal page _pages/" <> slug <> ".md collides with the declared special URL '" <> url <> "'"
        | (slug, _) <- normals
        , let url = "/" <> slug <> "/"
        , url `elem` map (canonical . snd) specials
        ]
    canonical :: CustomPage -> Text
    canonical page = fromMaybe "" (cpRedirectAs page)

findByURL :: Text -> [(Text, CustomPage)] -> Maybe (Text, CustomPage)
findByURL url = find ((== Just url) . cpRedirectAs . snd)

-- | All special pages, tagged with their file slug.
specialPages :: SitePages -> [(Text, CustomPage)]
specialPages sp =
    [ (slug, page)
    | mEntry <- [sp404 sp, spTags sp, spArchive sp, spSearch sp]
    , (slug, page) <- maybe [] pure mEntry
    ]

data NavEntry = NavEntry
    { entryLabel :: Text
    , entryHref :: Text
    , entryPriority :: Int
    , entrySlug :: Text
    }

{- | Navbar entries: normal pages plus the special pages (tags/archive/
search), sorted by (priority, slug); 404 is never in the navbar.
-}
navItems :: SitePages -> [(Text, Text)]
navItems sp =
    [ (entryLabel e, entryHref e)
    | e <- sortOn (\entry -> (entryPriority entry, entrySlug entry)) entries
    ]
  where
    entries :: [NavEntry]
    entries =
        concat
            [ [NavEntry (fromMaybe slug (cpTitle page)) ("/" <> slug <> "/") (cpPriority page) slug | (slug, page) <- spNormal sp]
            , specialEntry "/tags/" defaultTagsLabel (spTags sp)
            , specialEntry "/archive/" defaultArchiveTitle (spArchive sp)
            , specialEntry "/search/" defaultSearchTitle (spSearch sp)
            ]
    specialEntry :: Text -> Text -> Maybe (Text, CustomPage) -> [NavEntry]
    specialEntry href fallbackLabel mEntry =
        case mEntry of
            Nothing -> []
            Just (slug, page) -> [NavEntry (fromMaybe fallbackLabel (cpTitle page)) href (cpPriority page) slug]
