module Registry (SitePages (..), classifyPages, defaultArchiveTitle, defaultSearchTitle, defaultTagsLabel, navItems, specialPages) where

import Data.List (find, sortOn)
import Data.Maybe (fromMaybe)
import Data.Text (Text)
import Data.Text qualified as T
import Page (CustomPage (..))

{- | The classified pages: special pages (declared via redirectAs) are
pulled out of the normal page list, as are plain redirect stubs
(redirectAs pointing at any other / path or URL). Special pages and
redirect stubs keep their file slug.
-}
data SitePages = SitePages
    { sp404 :: Maybe (Text, CustomPage)
    , spTags :: Maybe (Text, CustomPage)
    , spArchive :: Maybe (Text, CustomPage)
    , spSearch :: Maybe (Text, CustomPage)
    , spIndex :: Maybe (Text, CustomPage)
    , spNormal :: [(Text, CustomPage)]
    , spRedirects :: [(Text, CustomPage)]
    }

{- | Registered special-page URLs. A page whose frontmatter declares one
of these via `redirectAs` becomes the corresponding special page; its
content is generated by burogu at that URL instead of the markdown body.
-}
specialURLs :: [(Text, Text)]
specialURLs = [("/404.html", "404"), ("/tags/", "tags"), ("/archive/", "archive"), ("/search/", "search"), ("/", "index")]

{- | A redirectAs target may be a site path (starting with /) or a
full URL (starting with http(s)://); any other form would produce an
invalid rel=canonical link.
-}
validRedirectTarget :: Text -> Bool
validRedirectTarget url = "/" `T.isPrefixOf` url || "http://" `T.isPrefixOf` url || "https://" `T.isPrefixOf` url

defaultTagsLabel :: Text
defaultTagsLabel = "Tags"

defaultArchiveTitle :: Text
defaultArchiveTitle = "Archive"

defaultSearchTitle :: Text
defaultSearchTitle = "Search"

{- | Classify loaded pages: validate the redirectAs declarations
(known URLs, no duplicates, no slug collisions) and split the special
pages and plain redirect stubs out.
-}
classifyPages :: [(Text, CustomPage)] -> Either [Text] SitePages
classifyPages pages
    | null errs = Right sitePages
    | otherwise = Left errs
  where
    specials = [(slug, page) | (slug, page) <- pages, isSpecial page]
    redirects = [(slug, page) | (slug, page) <- pages, isRedirect page]
    normals = [(slug, page) | (slug, page) <- pages, cpRedirectAs page == Nothing]
    isSpecial :: CustomPage -> Bool
    isSpecial page = cpRedirectAs page `elem` map (Just . fst) specialURLs
    isRedirect :: CustomPage -> Bool
    isRedirect page = case cpRedirectAs page of
        Just url -> url `notElem` map fst specialURLs && validRedirectTarget url
        Nothing -> False
    sitePages =
        SitePages
            { sp404 = findByURL "/404.html" specials
            , spTags = findByURL "/tags/" specials
            , spArchive = findByURL "/archive/" specials
            , spSearch = findByURL "/search/" specials
            , spIndex = findByURL "/" specials
            , spNormal = normals
            , spRedirects = redirects
            }
    errs = formatErrs <> duplicateErrs <> collisionErrs
    formatErrs =
        [ "invalid redirectAs '" <> url <> "' in _pages/" <> slug <> ".md (must start with / or http(s)://)"
        | (slug, page) <- pages
        , let url = canonical page
        , url /= ""
        , url `notElem` map fst specialURLs
        , not (validRedirectTarget url)
        ]
    duplicateErrs =
        [ "duplicate declaration of '" <> url <> "': used by " <> T.intercalate ", " ["_pages/" <> slug <> ".md" | slug <- users]
        | url <- map fst specialURLs
        , let users = [slug | (slug, page) <- specials, canonical page == url]
        , length users > 1
        ]
    collisionErrs =
        [ "normal page _pages/" <> slug <> ".md collides with the declared special URL '" <> url <> "'"
        | (slug, _) <- normals
        , let url = "/" <> slug <> "/"
        , url `elem` map (canonical . snd) specials
        ]
    canonical :: CustomPage -> Text
    canonical page = fromMaybe "" (cpRedirectAs page)

findByURL :: Text -> [(Text, CustomPage)] -> Maybe (Text, CustomPage)
findByURL url = find ((== Just url) . cpRedirectAs . snd)

-- | All special pages, tagged with their file slug.
specialPages :: SitePages -> [(Text, CustomPage)]
specialPages sp =
    [ (slug, page)
    | mEntry <- [sp404 sp, spTags sp, spArchive sp, spSearch sp, spIndex sp]
    , (slug, page) <- maybe [] pure mEntry
    ]

data NavEntry = NavEntry
    { entryLabel :: Text
    , entryHref :: Text
    , entryPriority :: Int
    , entrySlug :: Text
    , entryHidden :: Bool
    }

{- | Navbar entries: every page (normal pages, redirect stubs, and the
special pages tags/archive/search/404), sorted by (priority, slug).
Pages with `hiddenInNavbar: true` are left out.
-}
navItems :: SitePages -> [(Text, Text)]
navItems sp =
    [ (entryLabel e, entryHref e)
    | e <- sortOn (\entry -> (entryPriority entry, entrySlug entry)) entries
    , not (entryHidden e)
    ]
  where
    entries :: [NavEntry]
    entries =
        concat
            [ [NavEntry (fromMaybe slug (cpTitle page)) ("/" <> slug <> "/") (cpPriority page) slug (cpHiddenInNavbar page) | (slug, page) <- spNormal sp]
            , [NavEntry (fromMaybe slug (cpTitle page)) ("/" <> slug <> "/") (cpPriority page) slug (cpHiddenInNavbar page) | (slug, page) <- spRedirects sp]
            , specialEntry "/tags/" defaultTagsLabel (spTags sp)
            , specialEntry "/archive/" defaultArchiveTitle (spArchive sp)
            , specialEntry "/search/" defaultSearchTitle (spSearch sp)
            , specialEntry "/404.html" "404" (sp404 sp)
            ]
    -- the index page is the homepage itself; the site name links there
    specialEntry :: Text -> Text -> Maybe (Text, CustomPage) -> [NavEntry]
    specialEntry href fallbackLabel mEntry =
        case mEntry of
            Nothing -> []
            Just (slug, page) -> [NavEntry (fromMaybe fallbackLabel (cpTitle page)) href (cpPriority page) slug (cpHiddenInNavbar page)]
