module Site (BuildReport (..), SitePages (..), build, classifyPages, navItems) where

import Cli (Paths (..))
import Config (SiteConfig (..), Theme (..))
import Control.Exception (IOException, catch, throwIO)
import Css (renderCss)
import Data.List (find, sortOn)
import Data.Maybe (fromMaybe, isJust)
import Data.Text (Text)
import Data.Text qualified as T
import Data.Text.IO qualified as TIO
import Data.Text.Lazy qualified as TL
import Feed (renderAtom)
import Html qualified as H
import Lucid qualified as L
import Page (CustomPage (..), loadPages)
import Post (Post (..), mathMethod)
import Search qualified as S
import Sitemap (renderSitemap)
import System.Directory (
    copyFile,
    createDirectoryIfMissing,
    doesDirectoryExist,
    doesFileExist,
    listDirectory,
    removePathForcibly,
 )
import System.FilePath ((</>))

postsDirName :: FilePath
postsDirName = "posts"

data BuildReport = BuildReport
    { brStaticFiles :: Int
    , brTagPages :: Int
    , brFeed :: Bool
    , brSitemap :: Bool
    }

{- | The classified pages: special pages (declared via redirectAs) are
pulled out of the normal page list. Special pages keep their file slug.
-}
data SitePages = SitePages
    { sp404 :: Maybe (Text, CustomPage)
    , spTags :: Maybe (Text, CustomPage)
    , spArchive :: Maybe (Text, CustomPage)
    , spSearch :: Maybe (Text, CustomPage)
    , spNormal :: [(Text, CustomPage)]
    }

{- | Registered special-page URLs. A page whose frontmatter declares one
of these via `redirectAs` becomes the corresponding special page; its
content is generated by burogu at that URL instead of the markdown body.
-}
specialURLs :: [(Text, Text)]
specialURLs = [("/404.html", "404"), ("/tags/", "tags"), ("/archive/", "archive"), ("/search/", "search")]

specialURLList :: Text
specialURLList = T.intercalate ", " (map fst specialURLs)

defaultTagsLabel :: Text
defaultTagsLabel = "Tags"

defaultArchiveTitle :: Text
defaultArchiveTitle = "Archive"

defaultSearchTitle :: Text
defaultSearchTitle = "Search"

build :: Paths -> SiteConfig -> [Post] -> IO BuildReport
build paths config posts = do
    report <-
        buildWork paths config posts `catch` \(e :: IOException) -> do
            removePathForcibly (pOut paths)
            throwIO e
    pure report

buildWork :: Paths -> SiteConfig -> [Post] -> IO BuildReport
buildWork paths config posts = do
    validateExtraJs paths config
    let math = mathMethod (themeMath (siteTheme config)) (themeMathUrl (siteTheme config))
    let pagesDir = pSrc paths </> "_pages"
    epages <- loadPages math pagesDir
    case epages of
        Left errs -> ioError (userError (T.unpack (T.unlines (("_pages: " <>) <$> errs))))
        Right pages -> case classifyPages pages of
            Left errs -> ioError (userError (T.unpack (T.unlines (("_pages: " <>) <$> errs))))
            Right sp -> do
                let nav = navItems sp
                removePathForcibly (pOut paths)
                createDirectoryIfMissing True (pOut paths)
                TIO.writeFile (pOut paths </> "index.html") (TL.toStrict (L.renderText (H.renderIndex config nav posts)))
                write404 paths config nav (sp404 sp)
                writePages paths config nav (spNormal sp)
                writeRedirects paths (specialPages sp)
                writeStyleSheet paths config
                mapM_ (writePost paths config nav) posts
                writeTagPages paths config nav (spTags sp) posts
                writeArchive paths config nav (spArchive sp) posts
                writeSearch paths config nav sp posts
                writeRobots paths config
                brFeed <- writeFeed paths config posts
                brSitemap <- writeSitemap paths config posts nav (isJust (spTags sp))
                nStatic <- copyStatic paths
                pure BuildReport{brStaticFiles = nStatic, brTagPages = length (H.groupByTag posts), brFeed = brFeed, brSitemap = brSitemap}

{- | Classify loaded pages: validate the redirectAs declarations (known
URLs, no duplicates, no slug collisions) and split special pages out.
-}
classifyPages :: [(Text, CustomPage)] -> Either [Text] SitePages
classifyPages pages
    | null errs = Right sitePages
    | otherwise = Left errs
  where
    specials = [(slug, page) | (slug, page) <- pages, cpRedirectAs page /= Nothing]
    normals = [(slug, page) | (slug, page) <- pages, cpRedirectAs page == Nothing]
    sitePages =
        SitePages
            { sp404 = findByURL "/404.html" specials
            , spTags = findByURL "/tags/" specials
            , spArchive = findByURL "/archive/" specials
            , spSearch = findByURL "/search/" specials
            , spNormal = normals
            }
    errs = unknownURLErrs <> duplicateErrs <> collisionErrs
    unknownURLErrs =
        [ "unknown redirectAs '" <> url <> "' in _pages/" <> slug <> ".md (valid: " <> specialURLList <> ")"
        | (slug, page) <- specials
        , let url = canonical page
        , url `notElem` map fst specialURLs
        ]
    duplicateErrs =
        [ "duplicate declaration of '" <> url <> "': used by " <> T.intercalate ", " ["_pages/" <> slug <> ".md" | slug <- users]
        | url <- map fst specialURLs
        , let users = [slug | (slug, page) <- specials, canonical page == url]
        , length users > 1
        ]
    collisionErrs =
        [ "normal page _pages/" <> slug <> ".md collides with the declared special URL '" <> url <> "'"
        | (slug, _) <- normals
        , let url = "/" <> slug <> "/"
        , url `elem` map (canonical . snd) specials
        ]
    canonical :: CustomPage -> Text
    canonical page = fromMaybe "" (cpRedirectAs page)

findByURL :: Text -> [(Text, CustomPage)] -> Maybe (Text, CustomPage)
findByURL url = find ((== Just url) . cpRedirectAs . snd)

-- | All special pages, tagged with their file slug.
specialPages :: SitePages -> [(Text, CustomPage)]
specialPages sp =
    [ (slug, page)
    | mEntry <- [sp404 sp, spTags sp, spArchive sp, spSearch sp]
    , (slug, page) <- maybe [] pure mEntry
    ]

data NavEntry = NavEntry
    { entryLabel :: Text
    , entryHref :: Text
    , entryPriority :: Int
    , entrySlug :: Text
    }

{- | Navbar entries: normal pages plus the special pages (tags/archive),
sorted by (priority, slug); 404 is never in the navbar.
-}
navItems :: SitePages -> [(Text, Text)]
navItems sp =
    [ (entryLabel e, entryHref e)
    | e <- sortOn (\entry -> (entryPriority entry, entrySlug entry)) entries
    ]
  where
    entries :: [NavEntry]
    entries =
        concat
            [ [NavEntry (fromMaybe slug (cpTitle page)) ("/" <> slug <> "/") (cpPriority page) slug | (slug, page) <- spNormal sp]
            , specialEntry "/tags/" defaultTagsLabel (spTags sp)
            , specialEntry "/archive/" defaultArchiveTitle (spArchive sp)
            , specialEntry "/search/" defaultSearchTitle (spSearch sp)
            ]
    specialEntry :: Text -> Text -> Maybe (Text, CustomPage) -> [NavEntry]
    specialEntry href fallbackLabel mEntry =
        case mEntry of
            Nothing -> []
            Just (slug, page) -> [NavEntry (fromMaybe fallbackLabel (cpTitle page)) href (cpPriority page) slug]

write404 :: Paths -> SiteConfig -> [(Text, Text)] -> Maybe (Text, CustomPage) -> IO ()
write404 paths config nav mEntry =
    case mEntry of
        Just (_, page) ->
            TIO.writeFile (pOut paths </> "404.html") (TL.toStrict (L.renderText (H.renderCustomPage config nav pageMeta page)))
        Nothing ->
            TIO.writeFile (pOut paths </> "404.html") (TL.toStrict (L.renderText (H.render404 config nav)))
  where
    pageMeta :: H.PageMeta
    pageMeta =
        H.PageMeta
            { H.pmTitle = fromMaybe "404" (cpTitle =<< (snd <$> mEntry))
            , H.pmOgType = "website"
            , H.pmOgPath = "/404.html"
            , H.pmOgDescription = Nothing
            , H.pmHasMath = maybe False cpHasMath (snd <$> mEntry)
            }

writePages :: Paths -> SiteConfig -> [(Text, Text)] -> [(Text, CustomPage)] -> IO ()
writePages paths config nav pages =
    mapM_ writeOne pages
  where
    writeOne :: (Text, CustomPage) -> IO ()
    writeOne (slug, page) = do
        let dir = pOut paths </> T.unpack slug
        createDirectoryIfMissing True dir
        TIO.writeFile (dir </> "index.html") (TL.toStrict (L.renderText (H.renderCustomPage config nav pageMeta page)))
      where
        pageMeta :: H.PageMeta
        pageMeta =
            H.PageMeta
                { H.pmTitle = fromMaybe slug (cpTitle page)
                , H.pmOgType = "website"
                , H.pmOgPath = "/" <> slug <> "/"
                , H.pmOgDescription = Nothing
                , H.pmHasMath = cpHasMath page
                }

{- | Write redirect pages for special pages whose file slug differs
from their canonical URL.
-}
writeRedirects :: Paths -> [(Text, CustomPage)] -> IO ()
writeRedirects paths specials =
    mapM_ writeOne [(slug, page) | (slug, page) <- specials, "/" <> slug <> "/" /= canonical page]
  where
    canonical :: CustomPage -> Text
    canonical page = fromMaybe "" (cpRedirectAs page)
    writeOne :: (Text, CustomPage) -> IO ()
    writeOne (slug, page) = do
        let dir = pOut paths </> T.unpack slug
        createDirectoryIfMissing True dir
        TIO.writeFile (dir </> "index.html") (TL.toStrict (L.renderText (H.renderRedirect (canonical page))))

writeStyleSheet :: Paths -> SiteConfig -> IO ()
writeStyleSheet paths config = do
    extra <- mapM (readExtraCss . T.unpack) (themeExtraCss (siteTheme config))
    TIO.writeFile (pOut paths </> "style.css") (renderCss extra)
  where
    readExtraCss :: FilePath -> IO Text
    readExtraCss file = TIO.readFile (pSrc paths </> file)

validateExtraJs :: Paths -> SiteConfig -> IO ()
validateExtraJs paths config =
    mapM_ check (themeExtraJs (siteTheme config))
  where
    check :: Text -> IO ()
    check file = do
        exists <- doesFileExist (pSrc paths </> T.unpack file)
        if exists
            then pure ()
            else ioError (userError ("extra JS file not found in " <> pSrc paths <> ": " <> T.unpack file))

writePost :: Paths -> SiteConfig -> [(Text, Text)] -> Post -> IO ()
writePost paths config nav post = do
    let dir = pOut paths </> postsDirName </> T.unpack (postSlug post)
    createDirectoryIfMissing True dir
    TIO.writeFile (dir </> "index.html") (TL.toStrict (L.renderText (H.renderPost config nav post)))

writeTagPages :: Paths -> SiteConfig -> [(Text, Text)] -> Maybe (Text, CustomPage) -> [Post] -> IO ()
writeTagPages paths config nav mTagsPage posts =
    case mTagsPage of
        Nothing -> pure ()
        Just (_, page) -> do
            let label = fromMaybe defaultTagsLabel (cpTitle page)
                groups = H.groupByTag posts
                tagsDir = pOut paths </> T.unpack (T.dropWhile (== '/') (T.dropWhileEnd (== '/') H.tagUrlPrefix))
            createDirectoryIfMissing True tagsDir
            TIO.writeFile (tagsDir </> "index.html") (TL.toStrict (L.renderText (H.renderTagIndex config nav label groups)))
            mapM_ (writeTagPage config nav tagsDir) groups

writeTagPage :: SiteConfig -> [(Text, Text)] -> FilePath -> (Text, [Post]) -> IO ()
writeTagPage config nav tagsDir (tag, posts) = do
    let dir = tagsDir </> T.unpack tag
    createDirectoryIfMissing True dir
    TIO.writeFile (dir </> "index.html") (TL.toStrict (L.renderText (H.renderTagArchive config nav tag posts)))

writeArchive :: Paths -> SiteConfig -> [(Text, Text)] -> Maybe (Text, CustomPage) -> [Post] -> IO ()
writeArchive paths config nav mArchivePage posts =
    case mArchivePage of
        Nothing -> pure ()
        Just (_, page) -> do
            let dir = pOut paths </> "archive"
            createDirectoryIfMissing True dir
            TIO.writeFile (dir </> "index.html") (TL.toStrict (L.renderText (H.renderArchive config nav (fromMaybe defaultArchiveTitle (cpTitle page)) posts)))

writeSearch :: Paths -> SiteConfig -> [(Text, Text)] -> SitePages -> [Post] -> IO ()
writeSearch paths config nav sp posts =
    case spSearch sp of
        Nothing -> pure ()
        Just (_, page) -> do
            let dir = pOut paths </> "search"
            createDirectoryIfMissing True dir
            TIO.writeFile (dir </> "index.html") (TL.toStrict (L.renderText (H.renderSearch config nav (fromMaybe defaultSearchTitle (cpTitle page)))))
            TIO.writeFile (pOut paths </> "search.json") (S.renderSearchIndex posts (spNormal sp))

writeFeed :: Paths -> SiteConfig -> [Post] -> IO Bool
writeFeed paths config posts =
    case siteBaseUrl config of
        Just baseUrl
            | not (null posts) -> do
                TIO.writeFile (pOut paths </> "feed.xml") (renderAtom config baseUrl posts)
                pure True
        _ -> pure False

writeSitemap :: Paths -> SiteConfig -> [Post] -> [(Text, Text)] -> Bool -> IO Bool
writeSitemap paths config posts nav includeTags =
    case siteBaseUrl config of
        Just baseUrl
            | not (null posts) -> do
                TIO.writeFile (pOut paths </> "sitemap.xml") (renderSitemap baseUrl posts nav includeTags)
                pure True
        _ -> pure False

writeRobots :: Paths -> SiteConfig -> IO ()
writeRobots paths config =
    TIO.writeFile (pOut paths </> "robots.txt") $
        "User-agent: *\n"
            <> "Allow: /\n"
            <> maybe "" (\baseUrl -> "Sitemap: " <> baseUrl <> "/sitemap.xml\n") (siteBaseUrl config)

copyStatic :: Paths -> IO Int
copyStatic paths = do
    entries <- listDirectory (pSrc paths)
    let others = filter (`notElem` ["_post", "_pages"]) entries
    mapM_ (copyTree (pSrc paths) (pOut paths)) others
    pure (length others)

copyTree :: FilePath -> FilePath -> FilePath -> IO ()
copyTree srcBase dstBase name = do
    let source = srcBase </> name
        target = dstBase </> name
    isDir <- doesDirectoryExist source
    if isDir
        then do
            createDirectoryIfMissing True target
            children <- listDirectory source
            mapM_ (copyTree source target) children
        else copyFile source target
